apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - configmap-app.yaml
  - pvc.yaml
  - api-deployment.yaml
  - mlflow-deployment.yaml
  - prometheus-deployment.yaml
  - alertmanager-deployment.yaml
  - grafana-deployment.yaml
  - ingress.yaml
  - hpa-api.yaml
  - pdb-api.yaml
  - networkpolicy.yaml
  - retraining-cronjob.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=monitoring/prometheus/prometheus.yml
      - alert_rules.yml=monitoring/prometheus/alert_rules.yml
  - name: alertmanager-config
    files:
      - alertmanager.yml=monitoring/alertmanager/alertmanager.yml
  - name: grafana-datasources
    files:
      - prometheus.yml=monitoring/grafana/provisioning/datasources/prometheus.yml
  - name: grafana-dashboards-provisioning
    files:
      - dashboard.yml=monitoring/grafana/provisioning/dashboards/dashboard.yml
  - name: grafana-dashboard-json
    files:
      - mlops-monitoring.json=monitoring/grafana/dashboards/mlops-monitoring.json

generatorOptions:
  disableNameSuffixHash: true
